---
title: "Results"
author: "Nick Strayer"
date: "April 14, 2016"
output: pdf_document
---

## Results

The study divided the patients into two groups, a cohort that received lipids intravenously at some point during their admission and a control group that did not. The summary statistics from Table 1 suggest that the secondary variables: age, APACHE II score, gender, and BMI are balanced in proportion between the IVFE group and the control group. The confounding variables of total encounter length of stay, SICU length of stay, and total number of days on a ventilator are all unevenly distributed across the cohort and control groups. These variables are well established in the medical literature as contributing risk factors for hospital acquired infections. [CITATIONS]

Table: Patient Statistics.
|              |       Lipids| median|||     No Lipid| median|
|:-------------|------------:|------:|---|---|------------:|------:|
|Age           | 58.66 ± 1.27|  60.16||| 58.39 ± 0.84|   59.4|
|BMI           | 28.71 ± 0.77|  26.63||| 27.84 ± 0.44|   26.1|
|Glucose Level      | 170.55 ± 5.1| 160.00||| 189.73 ± 3.8|  176.0|
|Hospital Length of Stay      | 21.19 ± 1.19|  17.17||| 14.44 ± 0.72|   10.2|
|Unit Length of Stay     | 11.49 ± 0.84|   8.16|||  6.97 ± 0.36|    4.8|
|Days on Ventilator (Hospital) | 11.56 ± 1.06|   7.00|||  5.96 ± 0.58|    2.0|
|Days on Ventilator (Unit)|  8.52 ± 0.88|   4.81|||  3.38 ± 0.39|    0.9|
|Apache Score       | 18.97 ± 0.55|  18.00|||  17.2 ± 0.33|   17.0|

* \BMI = Weight(KG)/Height(M)$^2$.*

The similarity in the distribution of the secondary variables between the groups is further visualized in Figure 1. The figure suggests that these elements are well controlled for, and the study’s models need not account for them. 

>>Figure 1<<

  The outcome variables are not evenly distributed between case and control groups. The systemic, skin structure, and otolaryngology (Ear, Nose and Throat) infections did not meet the minimum threshold of 20 cases needed for sufficient power[CITATION]. The study did not attempt to model the effect of lipid emulsion on the risk of these infections.  

Table: Lipid Occurance and Infections. 

|                  | Occured| Did not Occur|
|:-----------------|-------:|-------------:|
|Lipid Emulsion                    |    1307|           538|
|Death in Hospital                 |    1683|           162|
|Death in Unit                     |    1740|           105|
|Blood Stream infection            |    1791|            54|
|Eye, Ear, Nose, Throat infection  |    1844|             1|
|Gastrointestinal  infection       |    1806|            39|
|Lower Resperatory infection       |    1831|            14|
|Pneumonia                         |    1706|           139|
|Surgical site infection           |    1796|            49|
|Skin structure infection          |    1844|             1|
|Systemic infection                |    1845|          1845|
|Urinary tract infection           |    1806|            39|

The confounding variables did not show signs of colinearity, as evidenced in Figure 2. This indicates that the model does not need interaction terms. Additionally the study was unable to conclude any significant marginal interactions between its predictors. 

>>Figure 2<<

	The study found that the use of a lipid emulsion increased the risk for hospital acquired blood-stream infections, lower-respiratory infections, surgical-site infections, and gastrointestinal infections. Lipid emulsions were not found to significantly affect the risk for hospital acquired pneumonia or urinary-tract infections. More information on these results including confidence interval bands for the odds ratios are shown in Table 3.   

Table: Model odds ratios.

|Infection Type    | Odds Ratio| 95% CI Lower| 95% CI Upper| P-Value| Hosmer-Lemeshow chi2 | 
|:-----------------|----------:|------------:|------------:|-------:|-------:|
|Bloodstream       |        1.9|         1.03|          3.3|   0.038| 0.021 |
|Lower respiratory |       13.0|         2.88|         58.6|   0.001| 0.003 |
|Pneumonia         |        1.5|         0.99|          2.3|   0.058| <0.001|
|Gastrointestinal  |        3.5|         1.75|          7.0|  <0.001| 0.081 |
|Surgical site     |        2.6|         1.47|          4.8|   0.001| 0.354 |
|UTI               |        1.7|         0.87|         3.36|   0.121| 0.068 |

*Hosmer-Lemeshow chi2 [@hosmer1997comparison] Figure 3 graphically displays these results*

>>Figure 3<<
